const hotelsData = [
    {
      id: 1,
      name: "The Grand Banashankari",
      offerPercentage: 20,
      address: "15th Cross, Banashankari 2nd Stage",
      city: "Bengaluru",
      postalCode: "560070",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn47pqz_b0U3isUmVAEEXA4s46IarxS00wOw&s",
      rating: 4.9,
  
    },
    {
      id: 2,
      name: "Cozy Stay Banashankari",
      offerPercentage: 15,
      address: "10th Main Road, Banashankari 3rd Stage",
      city: "Bengaluru",
      postalCode: "560085",
      imageUrl: "https://media.cntraveler.com/photos/654bd5e13892537a8ded0947/16:9/w_2560%2Cc_limit/phy2023.din.oss.restaurant-lr.jpg",
      rating: 4.7,
    },
    {
      id: 3,
      name: "Comfort Inn Bengaluru",
      offerPercentage: 25,
      address: "Banashankari 1st Stage",
      city: "Bengaluru",
      postalCode: "560050",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzJfzFjVVumyxfxiNZNAF6NmTKPm5IgOOQgA&s",
      rating: 4.9,

    },
    {
      id: 4,
      name: "Banashankari Residency",
      offerPercentage: 30,
      address: "5th Block, Banashankari 6th Stage",
      city: "Bengaluru",
      postalCode: "560098",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGnJgwXci_V6yg0xqSCqrzt2JOA1ekQG7kWw&s",
      rating: 3.9,

    },
    {
      id: 5,
      name: "South End Boutique Hotel",
      offerPercentage: 10,
      address: "Kanakapura Road, Near Banashankari Metro Station",
      city: "Bengaluru",
      postalCode: "560062",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn47pqz_b0U3isUmVAEEXA4s46IarxS00wOw&s",
      rating: 4.9,

    },
    {
      id: 6,
      name: "Elegance Hotel",
      offerPercentage: 35,
      address: "Outer Ring Road, Banashankari 5th Stage",
      city: "Bengaluru",
      postalCode: "560078",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2tYv2KwByu19FVKJiBJP9y6KpVVU_gTvy4Q&s",
      rating: 3.9,
    },
    {
        id: 7,
        name: "Matrica Hotel",
        offerPercentage: 40,
        address: "Kanakpura Road, JP Nagar",
        city: "Bengaluru",
        postalCode: "560078",
        imageUrl: "https://b.zmtcdn.com/data/pictures/9/20996449/da2ee37d49034be62aeb3d6a363f8c8e.jpg?fit=around|750:500&crop=750:500;*,*",
        rating: 4.8,

      },
      {
        id: 8,
        name: "Elegance Hotel",
        offerPercentage: 25,
        address: "Outer Ring Road, Banashankari 5th Stage",
        city: "Bengaluru",
        postalCode: "560111",
        imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2tYv2KwByu19FVKJiBJP9y6KpVVU_gTvy4Q&s",
        rating: 4.3,
      },
      {
          id: 9,
          name: "Matrica Hotel",
          offerPercentage: 45,
          address: "Kanakpura Road, JP Nagar",
          city: "Bengaluru",
          postalCode: "560111",
          imageUrl: "https://media.cntraveler.com/photos/654bd5e13892537a8ded0947/16:9/w_2560%2Cc_limit/phy2023.din.oss.restaurant-lr.jpg",
          rating: 4.8,
  
        },
        {
          id: 10,
          name: "Cozy Stay Banashankari",
          offerPercentage: 55,
          address: "10th Main Road, Banashankari 3rd Stage",
          city: "Bengaluru",
          postalCode: "560085",
          imageUrl: "https://b.zmtcdn.com/data/pictures/9/20996449/da2ee37d49034be62aeb3d6a363f8c8e.jpg?fit=around|750:500&crop=750:500;*,*",
          rating: 3.9,
        },

        {
          id: 10,
          name: "Cozy Stay Banashankari",
          offerPercentage: 55,
          address: "10th Main Road, Banashankari 3rd Stage",
          city: "Bengaluru",
          postalCode: "560085",
          imageUrl: "https://b.zmtcdn.com/data/pictures/9/20996449/da2ee37d49034be62aeb3d6a363f8c8e.jpg?fit=around|750:500&crop=750:500;*,*",
          rating: 3.9,
        },
  ];

  export default hotelsData;